### ISSUE TITLE
Adhere better to established conventions

### ISSUE THREAD

**Issue by stouset** [devalot/ror-example#1]
If you're making a tutorial app for newcomers, you should stick to the best practices and conventions agreed upon by the Rails and Ruby community (unless you have an explicit, intentional reason not to do so for certain cases).

A few things I noticed off the bat. You use a `before_filter` to set instance variables inside a [controller](https://github.com/devalot/ror-example/blob/master/app/controllers/refuels_controller.rb). This is generally bad practice — the folks at Rails Best Practices have highly downvoted a recommendation to do [exactly that](http://rails-bestpractices.com/posts/22-use-before_filter). My personal recommendation is in the comments of that post, but it boils down to: the contract between controller and view is instance variables. Contract fulfillment should be explicit.

Instead, define (memoized, ideally) a method that returns the collection object, and a method that returns the individual object (chained off the collection). Use these methods in the actions, and assign their return value to the expected instance variable.

Lastly, this is a minor nitpick, but you tend to overuse parentheses — for instance, around every call to `validates`, `has_many`, `belongs_to`, etc. in your models. This style is almost completely nonexistent in the greater community.

Again, there are very minor nitpicks. Were this your personal Rails application, it's of no issue what particular coding conventions you choose to use. However, when writing guides for newcomers, I firmly believe that one should attempt to advocate the conventions of the community as a whole. Any deviation that one feels is necessary or a clear improvement over the existing convention should be documented and explained.

Feel free to shitcan this issue if you disagree with that premise. I encourage you to give it some thought, though.

**Comment by devalot** [comment]
Stephen, thanks for the feedback.  I think it's fair to say your
comments can be summarized as a critique on style and I'll do my best
to address them.
1. The issue of creating instance variables inside a before filter
    is very valid.  I've certainly seen some crazy filters that
    contain way too much logic, and this is probably a good rule for
    beginners to follow.
   
    Ultimately I believe that simpler code should prevail.  In this
    case the before filter is only a single line and is pretty
    straight forward.  Being a tutorial of sorts, this code was
    helpful for demonstrating a before filter.
   
    That said, I see your point, and I may write additional comments
    for the authentication before filter as a way to demonstrate
    filters and then change the filter you are referencing so it's a
    memorizing private method.
2. To me, the parentheses are much more than a stylistic issue.  I
    realize I'm going against the grain here but I strongly believe
    that all Ruby developers should be using parentheses far more
    often.  
   
    Have you ever executed Ruby code with warnings enabled?  A lot of
    high-profile gems, when used with warnings enabled, produce a
    long list of warnings about possible ambiguities related to
    missing parentheses.  I've worked with seasoned Ruby developers
    that have introduced difficult to find bugs due to missing
    parentheses.  I could go on, but I think you get the picture.
   
    Using parentheses removes ambiguities, makes your code more
    explicit, and makes it easier to read, which makes it easier to
    maintain.

**Comment by stouset** [comment]
I still disagree, particularly so on the first issue (contract with the view should be explicit; my suggestion at least removes most duplication, but preserves explicit intent), but thanks for at least giving the points some consideration.

I also encourage you to keep in mind my greater recommendation: default to best practices, and at least mention and provide justifications when you feel it's worth diverging. :)

**Comment by devalot** [comment]
I agree with your assertion that controllers make a contract with
their views through instance variables and helper methods.  If I were
to rewrite that before filter as a private memorizing method it would
look something like this:

```
def car
  @car ||= current_user.cars.find(params[:car_id])
end

helper_method(:car)
```

And then I would need to change each of the controller's actions to
use this new method:

```
@refuel = car.refuels.create(params[:refuel])
```

It's possible (but maybe unlikely) that someone would write or modify
a controller action and not use the `car` method.  In this case the
`@car` instance variable wouldn't exist.  You should therefore update
the views so they use the `car` helper method instead of `@car`.

I would argue that if you see `@car` in a view you immediately know
that it came from a controller.  However, if you see `car` in a view
it could be a local variable, a method in any of the helper files, a
helper method in the controller, a helper method from the application
controller, a method from a plug-in, etc.  It's also much easier to
grep for `@car`.

While you've satisfied a best practice, you've also introduced an
ambiguity that makes the code harder to read.  Granted, this is a
somewhat contrived example, but I think the best practice of "write
the simplest code that works" takes precedence over "don't create
instance variables in before filters".

With this particular example (creating an instance variable in a
before filter because of a nested resource) I would say this technique
is in widespread use and to me doesn't feel like magic or isn't
explicit enough, quite the opposite.  The very first source line in
the controller tells you there's a before filter in effect and gives
you its name.  The filter itself is extremely clear.

Ultimately though I think we disagree because in this specific case
it's really a matter of style.  If the filter were more complicated
(e.g. had `:only` or `:except` conditions, were more than a single
line long, etc.) then I would say it's time to refactor it as a
private memorizing function.

**Comment by stouset** [comment]
Simpler is to do what I suggested in the linked page:

``` ruby
class RefuelController < ApplicationController
  extend ActiveSupport::Memoizable

  def index
    @car     = self.car
    @refuels = self.refuels
  end

  def show
    @car    = self.car
    @refuel = self.refuel
  end

  def new
    @car    = self.car
    @refuel = self.refuels.new params[:refuel]
  end

  # and so on

  protected

  def car
    self.current_user.cars.find params[:car_id]
  end

  def refuels
    self.car.refuels
  end

  def refuel
    self.refuels.find params[:id]
  end

  memoize :car
  memoize :refuels
  memoize :refuel
end
```

The instance variables are explicit (and must always be called), the views don't begin to expect that there are `helper_method`s and start circumventing the instance-variable contract, and duplication is kept to a minimum (minus the minimal duplication necessary for explicitness).

**Comment by stouset** [comment]
Also, everything there is side-effect free. :)

**Comment by pjones** [comment]
Yep, that's much better than what I posted in my last message.

**Comment by stouset** [comment]
And all the instance variables are visible up-front. Anyone writing the view can, at one quick glance, see all of the data they're intended to access in one convenient place: up top, at the beginning of the action.

Let me know if I should just shut up and move on. I'm only offering my suggestions with the expectation that you're interested. If you're not, that's fine and understandable.

**Comment by pjones** [comment]
I'm definitely interested in your perspective Stephen.  Your version is much more explicit and clean.  It seems a bit verbose but it's worth it.

**Comment by stouset** [comment]
Thanks. :)
